### ISSUE TITLE
API User Access Token Management v2 implementation

### ISSUE THREAD

**Issue by DonatienD** [tiktok/tiktok-business-api-sdk#11]
I'm trying to update a TikTok API integration, specifically, the *User Access Token Management* part, which has recently been updated to V2.

My application is a Ruby on Rails app, and I'm encountering an error when trying to fetch an access token using an authorization code.

Here's the V1 code that is working :

```ruby
def access_token_from(code)
    response = RestClient::Request.execute(
      method: :post,
      url: API_V1_BASE_URL + ACCESS_TOKEN_ENDPOINT +
      "?client_key=#{Rails.application.credentials.tiktok_client_key}" +
      "&client_secret=#{Rails.application.credentials.tiktok_client_secret}" +
      "&code=#{code}" +
      '&grant_type=authorization_code'
    )

    JSON.parse(response.body)
  end
```

And here's the updated non-working code :

```ruby
def manage_token_request(grant_type, params)
    url = API_V2_BASE_URL + ACCESS_TOKEN_ENDPOINT
    payload = {
      client_key: CLIENT_KEY,
      client_secret: CLIENT_SECRET,
      grant_type: grant_type
    }
    headers = {
      content_type: "application/x-www-form-urlencoded",
      cache_control: "no-cache",
    }

    if params[:code].present?
      payload.merge({ code: params[:code], redirect_uri: REDIRECT_URI })
    elsif params[:refresh_token].present?
      payload.merge({ refresh_token: params[:refresh_token] })
    end

    RestClient.post url, payload, headers
  end

  def access_token_from(code)
    response = manage_token_request(:authorization_code, { code: code })

    JSON.parse(response.body)
  end
```

The response I got by calling the API through this call is this :

```json
{
 "error"=>"invalid_request",
 "error_description"=>"The request parameters are malformed.",
 "log_id"=>"XXXXXXXXXXXXXXX"
}
```

Unfortunately, I can't get more details on the expected format of the parameters.

I've been trying tweaking everything but still got the same The request parameters are malformed. response.  
Note that executing the call on Postman works fine.

Is it possible to have further information on what is expected for the call to work (the [documentation](https://developers.tiktok.com/doc/oauth-user-access-token-management) doesn't provide further information)?

**Comment by jasonchentt** [comment]
> I'm trying to update a TikTok API integration, specifically, the _User Access Token Management_ part, which has recently been updated to V2.
> 
> My application is a Ruby on Rails app, and I'm encountering an error when trying to fetch an access token using an authorization code.
> 
> Here's the V1 code that is working :
> 
> ```ruby
> def access_token_from(code)
>     response = RestClient::Request.execute(
>       method: :post,
>       url: API_V1_BASE_URL + ACCESS_TOKEN_ENDPOINT +
>       "?client_key=#{Rails.application.credentials.tiktok_client_key}" +
>       "&client_secret=#{Rails.application.credentials.tiktok_client_secret}" +
>       "&code=#{code}" +
>       '&grant_type=authorization_code'
>     )
> 
>     JSON.parse(response.body)
>   end
> ```
> 
> And here's the updated non-working code :
> 
> ```ruby
> def manage_token_request(grant_type, params)
>     url = API_V2_BASE_URL + ACCESS_TOKEN_ENDPOINT
>     payload = {
>       client_key: CLIENT_KEY,
>       client_secret: CLIENT_SECRET,
>       grant_type: grant_type
>     }
>     headers = {
>       content_type: "application/x-www-form-urlencoded",
>       cache_control: "no-cache",
>     }
> 
>     if params[:code].present?
>       payload.merge({ code: params[:code], redirect_uri: REDIRECT_URI })
>     elsif params[:refresh_token].present?
>       payload.merge({ refresh_token: params[:refresh_token] })
>     end
> 
>     RestClient.post url, payload, headers
>   end
> 
>   def access_token_from(code)
>     response = manage_token_request(:authorization_code, { code: code })
> 
>     JSON.parse(response.body)
>   end
> ```
> 
> The response I got by calling the API through this call is this :
> 
> ```json
> {
>  "error"=>"invalid_request",
>  "error_description"=>"The request parameters are malformed.",
>  "log_id"=>"XXXXXXXXXXXXXXX"
> }
> ```
> 
> Unfortunately, I can't get more details on the expected format of the parameters.
> 
> I've been trying tweaking everything but still got the same The request parameters are malformed. response. Note that executing the call on Postman works fine.
> 
> Is it possible to have further information on what is expected for the call to work (the [documentation](https://developers.tiktok.com/doc/oauth-user-access-token-management) doesn't provide further information)?

Hello, thanks for providing the comments. It seems like you are using the wrong request param for "/oauth2/access_token" API. Please refer to https://business-api.tiktok.com/portal/docs?id=1739965703387137 for details of the request pramas.
