### ISSUE TITLE
Pytest Race Condition with ApiClient

### ISSUE THREAD

**Issue by HossameldeinDev** [tiktok/tiktok-business-api-sdk#14]
I get this timeout issue inconsistently when running my test cases. The issue comes from the ApiClient class -> "__del__" destructor when it waits forever. 

<img width="1503" alt="Screenshot 2023-10-06 at 2 20 38 AM" src="https://github.com/tiktok/tiktok-business-api-sdk/assets/20859983/494c0d0b-eaff-4087-a315-8414be01c1b5">

I'm not using the async calls from the library, I had to set this element to None to override the initialisation of the thread to make it work
```        
# Set the pool to None to avoid the threa lock issue as we are not using threads anyway
        self.api_client.pool = None
```

**Comment by jasonchentt** [comment]
Thanks for your reporting! We may update our docs to avoid future users meeting the same issue!
