### ISSUE TITLE
how do you gen swagger definition

### ISSUE THREAD

**Issue by wanghaisheng** [tiktok/tiktok-business-api-sdk#33]
>This Python package is automatically generated by the [Swagger Codegen](https://github.com/swagger-api/swagger-codegen) project:

I was start a similar project for https://github.com/wanghaisheng/tiktok-opensdk-web

can you share more detail about how do you guys start from a documentation to swagger json to use Codegen

**Comment by jasonchentt** [comment]
We generate the swagger files from internal API service (python) and internal parser service, not from Codegen.

**Comment by wanghaisheng** [comment]
could  you share the schema and swagger json for reference ?
I  find it hard start from raw documentation to do this @jasonchentt
