### ISSUE TITLE
Service ad preview on sandbox API Error 

### ISSUE THREAD

**Issue by Kigamekun** [tiktok/tiktok-business-api-sdk#34]
![Screenshot 2024-01-04 at 5 03 27 PM](https://github.com/tiktok/tiktok-business-api-sdk/assets/68811531/32b2ddc1-d615-4855-b3a6-be4abe43a860)

hello tiktok I use your api to create a campaign from my application and I want the ads I create to be able to be previewed, because in this SDK there is no preview function, finally I curl it manually with requests python, but for some reason I get that btw I use a sandbox account , what does that mean and what should I do even though the permissions in my token are already checked for that endpoint

<img width="1672" alt="Screenshot 2024-01-04 at 5 05 25 PM" src="https://github.com/tiktok/tiktok-business-api-sdk/assets/68811531/595ca916-7419-4b6b-871d-a9517e953e26">

**Comment by jasonchentt** [comment]
sandbox account is not supported in "/creative/ads_preview/create/" endpoint. You may try with actual account.
