### ISSUE TITLE
Pip - versioning and Support Please 2

### ISSUE THREAD

**Issue by Natgho** [tiktok/tiktok-business-api-sdk#38]
https://github.com/tiktok/tiktok-business-api-sdk/issues/4
I think it might be more functional to publish the package on pypi instead of silently closing the ticket :)

Please don't avoid the most basic things you need to do. Installing packages on Pypi is not that hard. A little effort...

**Comment by saivenkatmandava** [comment]
Hi Natgho,

Thanks for your suggestion. We are working on the Pypi publication. We understand the inconvenience, but please look forward for that update. Please, feel free to add any suggestions and feedback you have for us.

**Comment by saivenkatmandava** [comment]
@Natgho We have launched the pip library: tiktok-business-api-sdk-official v1.0.1
