### ISSUE TITLE
Pip - versioning and Support Please

### ISSUE THREAD

**Issue by Natgho** [tiktok/tiktok-business-api-sdk#4]
Please add package to the pip. 

In order for the system to be secure and stable, it is necessary to have a versioning system.

**Comment by jasonchentt** [comment]
Thanks for the suggestion and will include this in the future release. FYI, pip 23.0 will perfectly support current version of sdk

**Comment by stcalica** [comment]
This says closed, but it's still not in PyPI, correct? 
Do you recommend in the meantime to include into our projects as git submodule?

**Comment by Natgho** [comment]
No, not yet. Since it's a wrapper, the dev team is probably too lazy to prepare this package for pip. 

In fact, the team's answer is basically "fend for yourself."
