### ISSUE TITLE
What is the official pypi package link for the python SDK?

### ISSUE THREAD

**Issue by edpruuv** [tiktok/tiktok-business-api-sdk#41]
Hi, do you have a published [pypi python pakacge](https://pypi.org/) for the python SDK?

**Comment by jasonchentt** [comment]
> Hi, do you have a published [pypi python pakacge](https://pypi.org/) for the python SDK?



> Hi, do you have a published [pypi python pakacge](https://pypi.org/) for the python SDK?

Hi Edpruuv, we will release our official pypi package very soon. Will keep you posted and thanks!

**Comment by edpruuv** [comment]
Thanks @jasonchentt, looking forward to it!

**Comment by saivenkatmandava** [comment]
@edpruuv We have released the pip library: tiktok-business-api-sdk-official. Please use the latest version 1.0.1
