### ISSUE TITLE
API endpoint /open_api/v1.3/event/track/

### ISSUE THREAD

**Issue by samdaviestvg** [tiktok/tiktok-business-api-sdk#54]
Hi is there any plans on adding support for the API endpoint /open_api/v1.3/event/track/, specifically for python? I can see there's POST /open_api/v1.3/pixel/batch/ but going off of your developer docs this was sunset 2024 H2

**Comment by jasonchentt** [comment]
@samdaviestvg Yes, we do have plans to support more APIs including /open_api/v1.3/event/track/.  We currently estimate to support it Q1 in 2025!
