### ISSUE TITLE
/v1.3/campaign/get/ endpoint retrieve start and end date for the campaign 

### ISSUE THREAD

**Issue by HossameldeinDev** [tiktok/tiktok-business-api-sdk#7]
Can we add those two parameters to the response of this endpoint? 

{    "start_date": "2023-06-18",
    "end_date": "2023-06-25"
}
<img width="762" alt="Screenshot 2023-06-25 at 8 45 17 PM" src="https://github.com/tiktok/tiktok-business-api-sdk/assets/20859983/f7221baa-dd2e-4467-9494-759cb060e3a2">

**Comment by jasonchentt** [comment]
Currently, the downstream service does not support these two field info and we will keep this posted once these two fields are supported
