### ISSUE TITLE
Is there an enpoint to get the advertiser_ids user has access to?

### ISSUE THREAD

**Issue by psociety** [tiktok/tiktok-business-api-sdk#9]
Once you already got the access_token, how can you get an updated advertiser_ids list? 
(maybe the user has been added or removed from some of them).

All i see is the business_ids https://ads.tiktok.com/marketing_api/docs?id=1737115687501826
but i don't see any endpoint to get the same list you get when retrieving the access_token at  https://ads.tiktok.com/marketing_api/docs?id=1739965703387137

Would it be https://ads.tiktok.com/marketing_api/docs?id=1738455508553729 ?

**Comment by jasonchentt** [comment]
yes, oauth2/advertiser/get/ endpoint(https://business-api.tiktok.com/portal/docs?id=1738455508553729) will return you a list of advertisers that have granted you the permission to manage
